### ISSUE TITLE
Pseudolabelling Details

### ISSUE THREAD

**Issue by andydelworth** [tonyhuang2022/UPL#13]
Hi,

I am wondering if you could elaborate on your top-K pseudolabelling scheme. Mainly I am wondering, if an image is in the top-K for multiple classes, does it appear in the dataset multiple times, once for each class? Please let me know if this question makes sense.

Thanks,
Andy

**Comment by andydelworth** [comment]
Any pointers to the pseudolabelling code in your repo would be helpful as well, as I could not find it. Thanks!

**Comment by tonyhuang2022** [comment]
Thanks for your question. You can find the details of top-k selection in https://github.com/tonyhuang2022/UPL/blob/master/trainers/utils.py. We only select each image once.
