### ISSUE TITLE
Dassl version decreases the Acc on the StanfordCars dataset

### ISSUE THREAD

**Issue by machengcheng2016** [tonyhuang2022/UPL#2]
Greetings!
I can only get accs of ~47%/~54% with manual prompt/UPL on the StanfordCars dataset, based on RN50. 
However, the accs are ~55%/~62% as reported in the paper.
What's wrong?

**Comment by machengcheng2016** [comment]
I notice that CoOP supports the "prompt ensembling" trick, implemented as the `ZeroshotCLIP2` trainer. However, I still obtain a 48.24% acc, still far away from the ~55% as reported in the paper.
Please help me out :worried:

**Comment by tonyhuang2022** [comment]
Hi, do you just run our code or modify code before running? 
Is the performance of other datasets consistent with the paper in your experiments?

**Comment by machengcheng2016** [comment]
No I didnt modify any codes. 
For a second test, I just clone this project in an empty folder and conduct the experiments.
On the caltech101 dataset, I can get 87.06%/90.79% accuracy with original CLIP/UPL, based on RN50. Correspondingly, the accs are 86.09%/89.94% reported in your paper.
On the fgvc_aircraft dataset, I get 16.35% accuracy with original CLIP, and the official CLIP reported 16.92%.
So both caltech101 and fgvc_aircraft seem consistent. The performances on StanfordCars are really problematic.

**Comment by tonyhuang2022** [comment]
Thanks, I also think there is something wrong with the performance of StanfordCars in your experiments.

We know that,
1) other datasets' performance is consistent with what is posted in our paper;
2) both Zeroshot CLIP and UPL are problematic on Cars in your experiments;

So, I guess the dataset setting may cause the problem.
1. You can follow the dataset config of CoOp in [CoOp Datasets](https://github.com/KaiyangZhou/CoOp/blob/main/DATASETS.md) to ensure the correct dataset setting.
2. You can also use the original CLIP to check the zero-shot Acc on StanfordCars.

By the way, the performance we test on StanfordCars is 62.13 (UPL).

**Comment by machengcheng2016** [comment]
Thank you for your quick reply!
To be specific,
1. Actually, I indeed follow the dataset config of CoOp.
The folder of data/stanford_cars is like
![image](https://user-images.githubusercontent.com/22851860/172554992-50180093-928f-4fd6-92f0-49591880c61d.png)

2. I use the original CLIP to check the zero-shot Acc on StanfordCars by running
```
cd CoOp/scripts
bash zeroshot.sh stanford_cars rn50
```

Then I get results like
![1654672373(1)](https://user-images.githubusercontent.com/22851860/172554645-55d9e92a-f18c-440f-9ead-17e1829995c5.jpg)

I wonder how you use the original CLIP to check the zero-shot Acc on StanfordCars?

**Comment by tonyhuang2022** [comment]
Thanks.

Do you mean that you use original CoOp instead of CLIP? (though the CoOp uses the CLIP as the zero-shot predictor)

**So, whether it is zero-shot of [CoOp](https://github.com/KaiyangZhou/CoOp) or UPL, you cannot reproduce the accuracy of both?**

We have evaluated the zero-shot Acc with the original CLIP and the Acc is 55.64.

**Comment by machengcheng2016** [comment]
Yes, the accuracy of CLIP and UPL cannot be reproduced, and both of them drop ~8% from the reported ones.
Could you just show me how you evaluate the zero-shot Acc with the original CLIP?

**Comment by machengcheng2016** [comment]
You just use code from this repo, right? I am pretty sure that I have not changed any details, such as data aug and CLIP weights.

**Comment by tonyhuang2022** [comment]
I see you run the code from the original CoOp. We also get zero-shot Acc in this way.

**_Now, I think this is irrelevant with the UPL. The problems may exist in the dataset or dataset config._**

Would you mind provide your WeChat to [tonyhuang_pku@outlook.com](mailto:tonyhuang_pku@outlook.com)? And I will help you to solve the problem.

**Comment by tonyhuang2022** [comment]
Now, we realized that the dassl version cause the problem.
So, we recommend who meet the same problem update their dassl to the latest version.

(By the way, we use the version `git reset --hard ac6e44194b2f90e325f477aadd6d9bc3a92ce255` and all is OK in our experiments. But the same version is not work as @machengcheng2016 said, I still do not know why.)
