### ISSUE TITLE
Is Table-1 a fair comparison?

### ISSUE THREAD

**Issue by AadSah** [tonyhuang2022/UPL#4]
Hi

Thanks for the great work! In the paper it is mentioned that UPL uses 16-prompts for tuning, but in table-1, except UPL and UPL*, all other methods use a single prompt. I was just wondering if this is a fair comparison? Specifically, it increases the number of trainable parameters in UPL and UPL* and is expected to perform better. Also, running CoOp with 16-prompts is expected to perform even better. Would be great if you may clarify on this.

Thanks

**Comment by tonyhuang2022** [comment]
Thanks for your suggestions. We may add more comparison into the appendix. Specially, though the UPL and UPL* use the multiple prompts, they are all trained on the same pseudo-labeled images.

**Comment by tonyhuang2022** [comment]
Thanks for your suggestions. We may add more comparison into the appendix. Specially, though the UPL and UPL* use the multiple prompts, they are all trained on the same pseudo-labeled images.
