### ISSUE TITLE
IndexError at the start of training

### ISSUE THREAD

**Issue by altndrr** [tonyhuang2022/UPL#6]
Good afternoon,

During training, I get the error `IndexError: index X is out of bounds for axis 0 with size C` for every dataset I try. I manage to run the `get_info` script, but I cannot run the `upl_train` script because of the issue above, Below, you can find an example with the OxfordPets dataset.

```
Traceback (most recent call last):
  File "../upl_train.py", line 225, in <module>
    main(args)
  File "../upl_train.py", line 142, in main
    predict_label_dict, predict_conf_dict = trainer.load_from_exist_file(file_path='./analyze_results', 
  File "../trainers/upltrainer.py", line 593, in load_from_exist_file
    predict_label_dict, predict_conf_dict = select_top_k_similarity_per_class(logits, sstrain_img_paths, K=self.cfg.DATASET.NUM_SHOTS, is_softmax=False)
  File "../trainers/utils.py", line 98, in select_top_k_similarity_per_class
    img_paths = img_paths[output_m_max_id]
IndexError: index 1957 is out of bounds for axis 0 with size 37
```

From this snippet, it looks like it tries to index a sample inside a list containing an entry for every class (there are 37 classes in the OxfordPets dataset). The considered list is the `sstrain_img_paths` list, created by the `get_info` script and stored in the `.json` file. Given such information, I believe that maybe the `get_info` script should create an entry in the json for every sample in the dataset. **Can you confirm this? And can you suggest how to solve the issue?**

The commands I ran are:
```
CUDA_VISIBLE_DEVICES=0 bash get_info.sh ssoxford_pets anay_rn50 end 16 -1 False
CUDA_VISIBLE_DEVICES=0 bash upl_train.sh ssoxford_pets rn50_ep50 end 16 16 False True rn50_random_init
```

In addition, I also tried the version of dassl you suggested and the newest one. Below, you can also find the version of the libraries required for dassl and clip. I ran all the code on a NVIDIA RTX A4000.

```
python==3.9.7
ftfy==6.1.1
future==0.18.2
numpy==1.23.2
scikit-learn==1.1.2
scipy==1.9.1
tb-nightly==2.11.0a20220829
torch==1.12.1+cu113
torchvision==0.13.1+cu113
yacs==0.1.8
```

Many thanks,
Alessandro

**Comment by altndrr** [comment]
Good afternoon,

I was able to correct the issue. It was due to how path splitting is performed in the code. My local path is `/data/altndrr/source/UPL`. The presence of another `data` in the path brings problem when splitting the paths during the `get_info` script. The solution is to replace in the repo all the `split('/data/')[1]` occurrences with `split('/data/')[-1]`, to select the last element in the list and not the second.

Many thanks,
Alessandro

**Comment by muhammad-shahid0749** [comment]
Hi Alessandro, 

I am testing the code on my windows. I have changed the paths from "./data/" to ".\data\". But after this command "CUDA_VISIBLE_DEVICES=0 bash get_info.sh sscaltech101 anay_rn50 end 16 -1 False", I got the accuracy of 0.
