### ISSUE TITLE
Ask for hardware requirement such as  GPU

### ISSUE THREAD

**Issue by lijichang** [tonyhuang2022/UPL#8]
Hello, it's a pleasure to observe your very interesting and successful work.

This is my first step into the work of prompt learning, I am not very familiar with it. Therefore, I would like to ask you about the hardware conditions required by this work, for example, the GPU type and its memory required by each dataset.

Thanks a lot.

**Comment by tonyhuang2022** [comment]
Thanks, RTX3090 or V100 is enough for the all datasets.
