### ISSUE TITLE
How to do ensemble training?

### ISSUE THREAD

**Issue by LMC117** [tonyhuang2022/UPL#9]
Hello! I have the similar problem as another issue. I run UPL on my server and the accuracies on OxfordPets and StanfordCars datasets are 83.1 and 55.48 respectively, compared with 88.28 and 62.13 in the paper. The results of UPL* are also lower.

I use the latest version of dassl and the same experiment settings on the github page. So I wonder how to change parameters to do ensemble training (If I understand correctly, it means setting multiple prompts)?

By the way, to get the result in your paper's Table 3, is it necessary to set multiple (e.g. 16) prompts?

**Comment by tonyhuang2022** [comment]
Thanks.
Maybe you can test the accuracy on Pets and Cars of CoOp first.
We also training our UPL and UPL* with the same setting without adjusting parameters.

Yes, the UPL and UPL* both utilize the prompt ensemble, so you need to train 16 prompts as the paper said.
